/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: '#faf8f8',
        foreground: '#0f0b0c',
        black: '#0f0b0c',
        white: '#faf8f8',
        markup: '#e3dbdc',
        'markup-hover': '#34292a',
        'neutral-600': '#565051',
        'neutral-500': '#565051',
        'neutral-400': '#565051',
        border: '#e3dbdc',
        'border-hover': '#34292a',
      },
      fontFamily: {
        sans: ['EBGaramond', 'EB Garamond', 'Merriweather', 'PT Serif', 'Georgia', 'serif'],
        heading: ['Gloriascript', 'Pinyon Script', 'Playfair Display', 'serif'],
        accent: ['Gloriascript', 'cursive'],
        mono: ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Consolas', 'monospace'],
      },
      borderRadius: {
        none: '0px',
        DEFAULT: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '0px',
        'squircle-sm': '0px',
        'squircle': '0px',
        'squircle-md': '0px',
        'squircle-lg': '0px',
        'squircle-xl': '0px',
        'squircle-2xl': '0px',
        'squircle-3xl': '0px',
        'squircle-full': '0px',
      },
    },
  },
  plugins: [],
}
